---
title: "Day 7 Interactive"
author: "Matteo Torres"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# load packages
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

```{r}
penguins_tidy <- penguins %>%
  filter(island %in% c("Biscoe", "Dream")) %>%
  select(-year, -sex) %>%
  mutate(body_mass_kg = body_mass_g / 1000) %>%
  rename(location = island)
```

```{r}
adelie <- penguins %>%
  filter(species == "Adelie" & !is.na(flipper_length_mm)) %>%
  group_by(sex) %>%
  summarize(mean = mean(flipper_length_mm), 
            sd = sd(flipper_length_mm),
            sample_size = n())
```

```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )

sites <- tibble::tribble(
  ~location,      ~full_site_name, ~jurisdiction,
    "beach",       "Goleta Beach",     "SB City",
   "lagoon",        "UCSB Lagoon",        "UCSB",
    "bluff",       "Ellwood Mesa",     "SB City",
     "oaks", "Fremont Campground",        "USFS"
  )

```

```{r}
full_join_example <- full_join(animals, sites)
```

```{r}
left_join_example <- left_join(animals, sites)
```

```{r}
right_join_example <- right_join(animals, sites)
```

```{r}
inner_join_example <- inner_join(animals, sites)
```

```{r}
semi_join_example <- semi_join(animals, sites)
```

```{r}
anti_join_example <- anti_join(animals, sites, by = "location")
```

```{r}
sites <- sites %>%
  rename(place = location)

test_full_join <- full_join(animals, sites, by = c("location" = "place"))
```

```{r}
my_date <- "03-05-1998"
lubridate::mdy(my_date)

my_date <- "11/7/2003" # mdy
mdy(my_date)

my_date <- "08-Jun-1974" # dmy
dmy(my_date)

my_date <- "19610518" #ymd
date <- ymd(my_date)
class(date)
```

```{r}
time <- "2020-08-12 11:18"
time <- lubridate::ymd_hm(time)
class(time)

with_tz(time, "America/Los_Angeles")
with_tz(time, "Australia/Sydney")
```

```{r}
my_time <- lubridate::ymd_hms(time)

week(my_time)
hour(my_time)
day(my_time)
minute(my_time)
year(my_time)
month(my_time)
```

```{r}
comp_time_start <- Sys.time()
comp_time_end <- Sys.time()

comp_time_end - comp_time_start
```

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_counts <- urchin_counts %>%
  mutate(date = lubridate::mdy(date)) %>%
  mutate(year = year(date),
         month = month(date),
         day = day(date))

urchin_counts %>%
  group_by(year) %>%
  summarize(total = n())
```

```{r}
day_1 <- lubridate::ymd("2020-01-06")
day_2 <- lubridate::ymd("2020-05-18")
day_3 <- lubridate::ymd("2024-08-19")

time_interval <- interval(day_1, day_2)

time_length(time_interval, "day")
time_length(interval(day_2, day_3), "year")
```

```{r}
my_string <- "Teddy loves eating salmon and socks."

my_string %>%
  str_detect("love")
```

```{r}
my_string <- c("burrito", "fish taco", "taco salad")

my_string %>%
  str_detect("taco")
```

```{r}
skywalkers <- starwars %>%
  filter(str_detect(name, "Skywalker"))
```

```{r}
firewalkers <- starwars %>%
  mutate(name = str_replace(name, pattern = "Sky", replacement = "Fire"))
```

```{r}
feedback <- c(" I ate  some  nachos", "Wednesday morning   ")

str_squish(feedback)
str_trim(feedback)

str_to_lower(feedback)
str_to_upper(feedback)
str_to_title(feedback)
str_to_sentence(feedback)

str_count(feedback, pattern = "nachos")
```

